/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;


/**
 *
 * @author Fahrid
 */
public class home extends javax.swing.JFrame {
    controller.homeController controller = new controller.homeController(this);
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(home.class.getName());

    /**
     * Creates new form home
     */
    public home() {
        initComponents();
        controller.init();
        setSVG();
    }
    
    private void setSVG(){
        iconsvg_ofertas.setSVGImage("svg/library.svg", 30, 30);
        iconsvg_cofertas.setSVGImage("svg/assignment.svg", 30, 30);
        iconsvg_usuarios.setSVGImage("svg/users.svg", 30, 30);
        iconsvg_salida.setSVGImage("svg/leave.svg", 30, 30);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        contentpanel = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel6 = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        contentpanel_ofertas = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        boton_cursos = new jilmar.PanelRound();
        jLabel2 = new javax.swing.JLabel();
        boton_diplomados = new jilmar.PanelRound();
        jLabel4 = new javax.swing.JLabel();
        boton_talleres = new jilmar.PanelRound();
        jLabel3 = new javax.swing.JLabel();
        boton_seminarios = new jilmar.PanelRound();
        jLabel5 = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel();
        menupanel = new javax.swing.JPanel();
        boton_ofertas = new jilmar.PanelRound();
        iconsvg_ofertas = new custom.LabelSVG();
        jLabel1 = new javax.swing.JLabel();
        boton_cofertas = new jilmar.PanelRound();
        iconsvg_cofertas = new custom.LabelSVG();
        jLabel6 = new javax.swing.JLabel();
        boton_usuarios = new jilmar.PanelRound();
        iconsvg_usuarios = new custom.LabelSVG();
        jLabel7 = new javax.swing.JLabel();
        boton_salida = new jilmar.PanelRound();
        iconsvg_salida = new custom.LabelSVG();
        jLabel8 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        handybuttons_panel = new javax.swing.JPanel();
        boton_handy1 = new jilmar.PanelRound();
        iconsvg_handy1 = new custom.LabelSVG();
        jLabel9 = new javax.swing.JLabel();
        boton_handy2 = new jilmar.PanelRound();
        iconsvg_handy2 = new custom.LabelSVG();
        jLabel10 = new javax.swing.JLabel();
        boton_handy3 = new jilmar.PanelRound();
        iconsvg_handy3 = new custom.LabelSVG();
        jLabel11 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        contentpanel.setBackground(new java.awt.Color(255, 255, 255));
        contentpanel.setLayout(new java.awt.CardLayout());

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));

        jPanel5.setBackground(new java.awt.Color(204, 204, 204));
        jPanel5.setPreferredSize(new java.awt.Dimension(300, 400));
        jPanel5.setLayout(new java.awt.BorderLayout());

        jScrollPane2.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(jTable1);

        jPanel5.add(jScrollPane2, java.awt.BorderLayout.CENTER);

        jPanel6.setBackground(new java.awt.Color(204, 204, 204));

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 99, Short.MAX_VALUE)
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jPanel7.setBackground(new java.awt.Color(204, 204, 204));

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 141, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, 643, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        contentpanel.add(jPanel4, "control_academico");

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jPanel2.setOpaque(false);
        jPanel2.setLayout(new java.awt.BorderLayout());

        jScrollPane1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane1.setOpaque(false);

        javax.swing.GroupLayout contentpanel_ofertasLayout = new javax.swing.GroupLayout(contentpanel_ofertas);
        contentpanel_ofertas.setLayout(contentpanel_ofertasLayout);
        contentpanel_ofertasLayout.setHorizontalGroup(
            contentpanel_ofertasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 698, Short.MAX_VALUE)
        );
        contentpanel_ofertasLayout.setVerticalGroup(
            contentpanel_ofertasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 454, Short.MAX_VALUE)
        );

        jScrollPane1.setViewportView(contentpanel_ofertas);

        jPanel2.add(jScrollPane1, java.awt.BorderLayout.CENTER);

        jPanel3.setOpaque(false);

        boton_cursos.setBackground(new java.awt.Color(195, 22, 26));
        boton_cursos.setRoundBottomLeft(25);
        boton_cursos.setRoundTopLeft(25);
        boton_cursos.setLayout(new java.awt.BorderLayout());

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Cursos");
        boton_cursos.add(jLabel2, java.awt.BorderLayout.CENTER);

        boton_diplomados.setBackground(new java.awt.Color(195, 22, 26));
        boton_diplomados.setLayout(new java.awt.BorderLayout());

        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Diplomados");
        boton_diplomados.add(jLabel4, java.awt.BorderLayout.CENTER);

        boton_talleres.setBackground(new java.awt.Color(195, 22, 26));
        boton_talleres.setLayout(new java.awt.BorderLayout());

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Talleres");
        boton_talleres.add(jLabel3, java.awt.BorderLayout.CENTER);

        boton_seminarios.setBackground(new java.awt.Color(195, 22, 26));
        boton_seminarios.setRoundBottomRight(25);
        boton_seminarios.setRoundTopRight(25);
        boton_seminarios.setLayout(new java.awt.BorderLayout());

        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Seminarios");
        boton_seminarios.add(jLabel5, java.awt.BorderLayout.CENTER);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 579, Short.MAX_VALUE)
            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel3Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(boton_cursos, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, 0)
                    .addComponent(boton_diplomados, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, 0)
                    .addComponent(boton_talleres, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, 0)
                    .addComponent(boton_seminarios, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 40, Short.MAX_VALUE)
            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel3Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(boton_cursos, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(boton_diplomados, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(boton_talleres, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(boton_seminarios, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(30, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 700, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(55, 55, 55)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(30, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        contentpanel.add(jPanel1, "control_ofertas");

        jPanel8.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 760, Short.MAX_VALUE)
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 562, Short.MAX_VALUE)
        );

        contentpanel.add(jPanel8, "control_usuarios");

        getContentPane().add(contentpanel, java.awt.BorderLayout.CENTER);

        menupanel.setBackground(new java.awt.Color(51, 51, 51));
        menupanel.setPreferredSize(new java.awt.Dimension(200, 540));

        boton_ofertas.setBackground(model.config.menugray);
        boton_ofertas.setPreferredSize(new java.awt.Dimension(175, 50));
        boton_ofertas.setRoundBottomLeft(10);
        boton_ofertas.setRoundBottomRight(10);
        boton_ofertas.setRoundTopLeft(10);
        boton_ofertas.setRoundTopRight(10);
        boton_ofertas.setLayout(new java.awt.BorderLayout());

        iconsvg_ofertas.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        iconsvg_ofertas.setPreferredSize(new java.awt.Dimension(45, 45));
        boton_ofertas.add(iconsvg_ofertas, java.awt.BorderLayout.LINE_START);

        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Ofertas Académicas");
        boton_ofertas.add(jLabel1, java.awt.BorderLayout.CENTER);

        boton_cofertas.setBackground(model.config.menugray);
        boton_cofertas.setPreferredSize(new java.awt.Dimension(175, 50));
        boton_cofertas.setRoundBottomLeft(10);
        boton_cofertas.setRoundBottomRight(10);
        boton_cofertas.setRoundTopLeft(10);
        boton_cofertas.setRoundTopRight(10);
        boton_cofertas.setLayout(new java.awt.BorderLayout());

        iconsvg_cofertas.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        iconsvg_cofertas.setPreferredSize(new java.awt.Dimension(45, 45));
        boton_cofertas.add(iconsvg_cofertas, java.awt.BorderLayout.LINE_START);

        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Creaciones Académicas");
        boton_cofertas.add(jLabel6, java.awt.BorderLayout.CENTER);

        boton_usuarios.setBackground(model.config.menugray);
        boton_usuarios.setPreferredSize(new java.awt.Dimension(175, 50));
        boton_usuarios.setRoundBottomLeft(10);
        boton_usuarios.setRoundBottomRight(10);
        boton_usuarios.setRoundTopLeft(10);
        boton_usuarios.setRoundTopRight(10);
        boton_usuarios.setLayout(new java.awt.BorderLayout());

        iconsvg_usuarios.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        iconsvg_usuarios.setPreferredSize(new java.awt.Dimension(45, 45));
        boton_usuarios.add(iconsvg_usuarios, java.awt.BorderLayout.LINE_START);

        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Usuarios del Sistema");
        boton_usuarios.add(jLabel7, java.awt.BorderLayout.CENTER);

        boton_salida.setBackground(model.config.menugray);
        boton_salida.setPreferredSize(new java.awt.Dimension(175, 50));
        boton_salida.setRoundBottomLeft(10);
        boton_salida.setRoundBottomRight(10);
        boton_salida.setRoundTopLeft(10);
        boton_salida.setRoundTopRight(10);
        boton_salida.setLayout(new java.awt.BorderLayout());

        iconsvg_salida.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        iconsvg_salida.setPreferredSize(new java.awt.Dimension(45, 45));
        boton_salida.add(iconsvg_salida, java.awt.BorderLayout.LINE_START);

        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Salir y guardar cambios");
        boton_salida.add(jLabel8, java.awt.BorderLayout.CENTER);

        jSeparator1.setForeground(new java.awt.Color(102, 102, 102));

        handybuttons_panel.setBackground(new java.awt.Color(255, 0, 0));

        boton_handy1.setBackground(model.config.menugray);
        boton_handy1.setPreferredSize(new java.awt.Dimension(175, 50));
        boton_handy1.setRoundBottomLeft(10);
        boton_handy1.setRoundBottomRight(10);
        boton_handy1.setRoundTopLeft(10);
        boton_handy1.setRoundTopRight(10);
        boton_handy1.setLayout(new java.awt.BorderLayout());

        iconsvg_handy1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        iconsvg_handy1.setPreferredSize(new java.awt.Dimension(45, 45));
        boton_handy1.add(iconsvg_handy1, java.awt.BorderLayout.LINE_START);

        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("botón práctico 1");
        boton_handy1.add(jLabel9, java.awt.BorderLayout.CENTER);

        boton_handy2.setBackground(model.config.menugray);
        boton_handy2.setPreferredSize(new java.awt.Dimension(175, 50));
        boton_handy2.setRoundBottomLeft(10);
        boton_handy2.setRoundBottomRight(10);
        boton_handy2.setRoundTopLeft(10);
        boton_handy2.setRoundTopRight(10);
        boton_handy2.setLayout(new java.awt.BorderLayout());

        iconsvg_handy2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        iconsvg_handy2.setPreferredSize(new java.awt.Dimension(45, 45));
        boton_handy2.add(iconsvg_handy2, java.awt.BorderLayout.LINE_START);

        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("botón práctico 2");
        boton_handy2.add(jLabel10, java.awt.BorderLayout.CENTER);

        boton_handy3.setBackground(model.config.menugray);
        boton_handy3.setPreferredSize(new java.awt.Dimension(175, 50));
        boton_handy3.setRoundBottomLeft(10);
        boton_handy3.setRoundBottomRight(10);
        boton_handy3.setRoundTopLeft(10);
        boton_handy3.setRoundTopRight(10);
        boton_handy3.setLayout(new java.awt.BorderLayout());

        iconsvg_handy3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        iconsvg_handy3.setPreferredSize(new java.awt.Dimension(45, 45));
        boton_handy3.add(iconsvg_handy3, java.awt.BorderLayout.LINE_START);

        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("botón práctico 3");
        boton_handy3.add(jLabel11, java.awt.BorderLayout.CENTER);

        javax.swing.GroupLayout handybuttons_panelLayout = new javax.swing.GroupLayout(handybuttons_panel);
        handybuttons_panel.setLayout(handybuttons_panelLayout);
        handybuttons_panelLayout.setHorizontalGroup(
            handybuttons_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(handybuttons_panelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(handybuttons_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(boton_handy1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(boton_handy2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(boton_handy3, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addContainerGap())
        );
        handybuttons_panelLayout.setVerticalGroup(
            handybuttons_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(handybuttons_panelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(boton_handy1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(boton_handy2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(boton_handy3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout menupanelLayout = new javax.swing.GroupLayout(menupanel);
        menupanel.setLayout(menupanelLayout);
        menupanelLayout.setHorizontalGroup(
            menupanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(menupanelLayout.createSequentialGroup()
                .addContainerGap(8, Short.MAX_VALUE)
                .addGroup(menupanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(boton_cofertas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(boton_ofertas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(boton_usuarios, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(boton_salida, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(handybuttons_panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(17, Short.MAX_VALUE))
        );
        menupanelLayout.setVerticalGroup(
            menupanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(menupanelLayout.createSequentialGroup()
                .addContainerGap(35, Short.MAX_VALUE)
                .addComponent(boton_ofertas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(boton_cofertas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(boton_usuarios, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(handybuttons_panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 55, Short.MAX_VALUE)
                .addComponent(boton_salida, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(16, 16, 16))
        );

        getContentPane().add(menupanel, java.awt.BorderLayout.WEST);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public jilmar.PanelRound boton_cofertas;
    public jilmar.PanelRound boton_cursos;
    public jilmar.PanelRound boton_diplomados;
    public jilmar.PanelRound boton_handy1;
    public jilmar.PanelRound boton_handy2;
    public jilmar.PanelRound boton_handy3;
    public jilmar.PanelRound boton_ofertas;
    public jilmar.PanelRound boton_salida;
    public jilmar.PanelRound boton_seminarios;
    public jilmar.PanelRound boton_talleres;
    public jilmar.PanelRound boton_usuarios;
    public javax.swing.JPanel contentpanel;
    public javax.swing.JPanel contentpanel_ofertas;
    public javax.swing.JPanel handybuttons_panel;
    public custom.LabelSVG iconsvg_cofertas;
    public custom.LabelSVG iconsvg_handy1;
    public custom.LabelSVG iconsvg_handy2;
    public custom.LabelSVG iconsvg_handy3;
    public custom.LabelSVG iconsvg_ofertas;
    public custom.LabelSVG iconsvg_salida;
    public custom.LabelSVG iconsvg_usuarios;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTable jTable1;
    public javax.swing.JPanel menupanel;
    // End of variables declaration//GEN-END:variables
}
