/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

/**
 *
 * @author Fahrid
 */
public class home extends javax.swing.JFrame {
    controller.homeController controller = new controller.homeController(this);
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(home.class.getName());

    /**
     * Creates new form home
     */
    public home() {
        initComponents();
        controller.expandMenu();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        menu_panel = new jilmar.PanelRound();
        contentbutton = new javax.swing.JPanel();
        back_uv = new javax.swing.JPanel();
        icon_uv = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        labelRound5 = new jilmar.LabelRound();
        labelRound6 = new jilmar.LabelRound();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new java.awt.CardLayout());

        jPanel1.setPreferredSize(new java.awt.Dimension(960, 540));
        jPanel1.setLayout(new java.awt.BorderLayout());

        jPanel2.setPreferredSize(new java.awt.Dimension(80, 100));

        menu_panel.setBackground(new java.awt.Color(195, 22, 26));
        menu_panel.setPreferredSize(new java.awt.Dimension(70, 70));
        menu_panel.setRoundBottomLeft(25);
        menu_panel.setRoundBottomRight(25);
        menu_panel.setRoundTopLeft(25);
        menu_panel.setRoundTopRight(25);
        menu_panel.setLayout(new java.awt.BorderLayout());

        contentbutton.setBackground(new java.awt.Color(195, 22, 26));
        contentbutton.setOpaque(false);
        contentbutton.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        back_uv.setBackground(new java.awt.Color(166, 19, 22));
        back_uv.setOpaque(false);
        back_uv.setPreferredSize(new java.awt.Dimension(50, 50));
        back_uv.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        icon_uv.setBackground(new java.awt.Color(255, 51, 255));
        icon_uv.setOpaque(true);
        back_uv.add(icon_uv, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 50, 50));

        contentbutton.add(back_uv, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 430, 70, 70));

        menu_panel.add(contentbutton, java.awt.BorderLayout.PAGE_END);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(menu_panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(135, Short.MAX_VALUE)
                .addComponent(menu_panel, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(5, 5, 5))
        );

        jPanel1.add(jPanel2, java.awt.BorderLayout.WEST);

        labelRound5.setBackground(new java.awt.Color(255, 255, 0));
        labelRound5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelRound5.setRoundBottomLeft(100);
        labelRound5.setRoundBottomRight(100);
        labelRound5.setRoundTopLeft(100);
        labelRound5.setRoundTopRight(100);

        labelRound6.setBackground(new java.awt.Color(255, 255, 0));
        labelRound6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelRound6.setRoundBottomLeft(100);
        labelRound6.setRoundBottomRight(100);
        labelRound6.setRoundTopLeft(100);
        labelRound6.setRoundTopRight(100);

        jButton1.setText("jButton1");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap(508, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addComponent(jButton1)
                        .addGap(297, 297, 297))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addComponent(labelRound5, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(labelRound6, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30))))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(129, 129, 129)
                .addComponent(jButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 268, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelRound5, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelRound6, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20))
        );

        jPanel1.add(jPanel3, java.awt.BorderLayout.CENTER);

        getContentPane().add(jPanel1, "card2");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JPanel back_uv;
    public javax.swing.JPanel contentbutton;
    public javax.swing.JLabel icon_uv;
    private javax.swing.JButton jButton1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    public jilmar.LabelRound labelRound5;
    public jilmar.LabelRound labelRound6;
    private jilmar.PanelRound menu_panel;
    // End of variables declaration//GEN-END:variables
}
