/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package view.template;

import java.awt.Color;

/**
 *
 * @author Fahrid
 */
public class AccessControlButtonModel extends javax.swing.JPanel {

    /**
     * Creates new form AccessControlButtonModel
     * @param text texto descriptivo del boton rojo de acceso
     * @param color color del boton (normalmente rojo univalluno)
     */
    public AccessControlButtonModel(String text, Color color) {
        initComponents();
        texto.setText(text);
        setColor(color); 
    }
    
    private void setColor(Color c){
        boton.setBackground(c);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        boton = new jilmar.PanelRound();
        texto = new javax.swing.JLabel();

        setPreferredSize(new java.awt.Dimension(140, 50));

        boton.setPreferredSize(new java.awt.Dimension(130, 40));
        boton.setRoundBottomLeft(10);
        boton.setRoundBottomRight(10);
        boton.setRoundTopLeft(10);
        boton.setRoundTopRight(10);
        boton.setLayout(new java.awt.BorderLayout());

        texto.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        texto.setForeground(new java.awt.Color(255, 255, 255));
        texto.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        texto.setText("jLabel1");
        boton.add(texto, java.awt.BorderLayout.CENTER);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(boton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(boton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public jilmar.PanelRound boton;
    public javax.swing.JLabel texto;
    // End of variables declaration//GEN-END:variables
}
