/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package view.template;

/**
 *
 * @author Fahrid
 */
public class TabButtonModel extends javax.swing.JPanel {

    /**
     * Creates new form ButtonModel
     * @param text texto descriptivo de la acción del botón
     * @param svgdir directorio donde se ubica el pictograma
     * @param size dimensiones para el pictograma
     */
    public TabButtonModel(String text, String svgdir, int size) {
        initComponents();
        setTitle(text);
        view.Home.setSVG(icono, svgdir, size);
    }
    
    private void setTitle(String text){
        this.titulo.setText(String.format("<html><p>%s</p></html>", text));
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        boton = new jilmar.PanelRound();
        titulo = new javax.swing.JLabel();
        icono = new custom.LabelSVG();

        boton.setBackground(new view.Home().menupanel.getBackground());
        boton.setPreferredSize(new java.awt.Dimension(175, 50));
        boton.setRoundBottomLeft(10);
        boton.setRoundBottomRight(10);
        boton.setRoundTopLeft(10);
        boton.setRoundTopRight(10);
        boton.setLayout(new java.awt.BorderLayout());

        titulo.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        titulo.setForeground(new java.awt.Color(255, 255, 255));
        titulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        titulo.setText("AAAAAAAAAAAAAAA");
        boton.add(titulo, java.awt.BorderLayout.CENTER);

        icono.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        icono.setPreferredSize(new java.awt.Dimension(50, 50));
        boton.add(icono, java.awt.BorderLayout.LINE_START);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(boton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(boton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public jilmar.PanelRound boton;
    public custom.LabelSVG icono;
    public javax.swing.JLabel titulo;
    // End of variables declaration//GEN-END:variables
}
